name: Bo3 NaVi Calendar Bot

on:
  schedule:
    - cron: "0 */6 * * *"   # запуск кожні 6 годин
  workflow_dispatch:         # можливість запускати вручну

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        env:
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
          SCRAPED_TIME_IS_UTC: "true"  
        run: python bo3_calendar.py
